name: PR - Build / Test - Composite action

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Before Composite action
        run: |
          echo "Hello from before composite action"

      - name: Build and Publish .NET Core App
        uses: devopselvis/github-actions-presentation-2025/.github/actions/build-and-publish@main
        with:
          dotnet-version: "8.0.x"
          project-path: "${{ github.workspace }}/src/my-web-app/my-web-app.csproj"
          output-path: "mywebapp"

      - name: After Composite action
        run: |
          echo "Hello from after composite action"
